name: Run Script for Task3

on: [push,pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run the script
        run: |
          chmod +x tasks/task3a.sh
          chmod +x tasks/task3b.sh
          chmod +x tasks/task3c.sh
          chmod +x tasks/task3.sh
          ./task3.sh