name: Run Script for Task1

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Run the script
        run: |
          chmod +x ./tasks/task1.sh
          chmod +x infinite.sh
          ./infinite.sh && ./tasks/task1.sh
