name: Run Script for Task2

on: [push,pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run the scripts
        run: |
          chmod +x ./tasks/task2a.sh
          chmod +x ./tasks/task2b.sh
          chmod +x ./tasks/task2c.sh
          chmod +x ./tasks/task2.sh
          ./tasks/task2.sh
